name: Docker

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  ALIYUN_HUB_NAME: "${{ secrets.ALIYUN_HUB_NAME }}"
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"
  HEARTCHECK_URL: "${{ secrets.HEARTCHECK_URL }}"
  PUSHDEER_URL: "${{ secrets.PUSHDEER_URL }}"
  PUSHDEER_API_KEY: "${{ secrets.PUSHDEER_API_KEY }}"
  
jobs:

  build:
    name: Pull and Push Docker Images
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Replace USERNAME_PLACEHOLDER
      run: bash replace_username.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Create a new builder instance
      run: docker buildx create --use

    - name: Inspect builder instance
      run: docker buildx inspect --bootstrap
      
    - name: Login to Docker registry
      run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u $ALIYUN_REGISTRY_USER --password-stdin $REGISTRY
    
    - name: Build and push image to ACR EE
      run: |
        bash pull.sh
        data=`cat trigger.txt`
        curl -X POST $PUSHDEER_URL \
             -d "pushkey=$PUSHDEER_API_KEY" \
             -d "text=镜像同步成功！"

    - name: Send Heartcheck
      run: |
        curl -X GET $HEARTCHECK_URL
